### ISSUE TITLE
game does not run

### ISSUE THREAD

**Issue by abprince** [northoniserhardt/tiktok-live-game#1]
i followed all the steps when i run the server.js and open the frontend nothing happened

**Comment by northoniserhardt** [comment]
Hello abprince, thanks for your feedback, have you updated the .env?
The front started right? Did you manage to see the characters?

**Comment by abprince** [comment]
I followed all the steps what you have mentioned in the repo unfortunately front did not start

**Comment by northoniserhardt** [comment]
Oh, I got you, making some changes in repo to make it less complicated.
When I'm done, I'll let you know.

**Comment by northoniserhardt** [comment]
Done!
Updated the code and read.md
I suggest resposive 465x906

**Comment by abprince** [comment]
Now the front page is working but how can I connect it  to Tiktok and
check the interactive game.

**Comment by northoniserhardt** [comment]
Just update the tiktok ID of the live you want to connect in .env
